[package]
name = "keychat_rust_ffi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.7.0"
nostr = {version = "0.33", default-features = false, features = ["std", "nip04", "nip06", "nip44", "nip59"] }

